services:
  - type: web
    name: mlflow-server
    env: python
    plan: free
    runtime: python-3.11.9
    buildCommand: pip install -r src/mlflow_server/requirements.txt
    startCommand: bash src/mlflow_server/app.sh